name: Caller Workflow

on:
  push:

jobs:
  call-workflow-1-in-local-repo:
    uses: nasir17git/defefwwef/.github/workflows/call.yaml@main
    with:
      username: nasir
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/called.yaml
    with:
      username: mona
    secrets:
      SECRET_SEED: seed